const { env } = process;

module.exports = {
  PORT: env.PORT,
  NODE_ENV: env.NODE_ENV,
  MONGODB_URI: env.MONGODB_URI,
  CLOUDINARY_CLOUD_NAME: env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: env.CLOUDINARY_API_SECRET,
  CLIENTNAME: env.CLIENTNAME,
  EBULKY_USER_NAME: env.EBULKY_USER_NAME,
  EBULKY_API: env.EBULKY_API,
  FLW_SECRET_HASH: env.FLW_SECRET_HASH,
  MAIL_AUTH_USER: env.MAIL_AUTH_USER,
  MAIL_AUTH_PASS: env.MAIL_AUTH_PASS,
  JWT_KEY: env.JWT_KEY,
};
